lab1:
	bash ./test_data.sh Lab1
	sbt 'Test/runMain acal_lab08.topTest'
lab2:
	bash ./test_data.sh Lab2
	sbt 'Test/runMain acal_lab08.topTest'
hw1:
	bash ./test_data.sh Hw2
	sbt 'Test/runMain acal_lab08.topTest'
hw2:
	bash ./test_data.sh Hw2
	sbt 'Test/runMain acal_lab08.topTest'
clean:
	rm -rf project
	rm -rf test_run_dir
	rm -rf target